version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /workspaces/workspace/database/database.sqlite
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
    ports:
      - "5000:5000"
      - "5173:5173"
